from . import db


class AADFByDirection(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    count_point_id = db.Column(db.Integer, nullable=False)
    year = db.Column(db.String(length=4), nullable=False)
    region_id = db.Column(db.Integer, nullable=False)
    region_name = db.Column(db.String(length=50), nullable=False)
    local_authority_id = db.Column(db.Integer, nullable=False)
    local_authority_name = db.Column(db.String(length=50), nullable=False)
    road_name = db.Column(db.String(length=50), nullable=False)
    road_type = db.Column(db.String(length=10), nullable=False)
    start_junction_road_name = db.Column(db.String(length=50))
    end_junction_road_name = db.Column(db.String(length=50))
    easting = db.Column(db.Integer, nullable=False)
    northing = db.Column(db.Integer, nullable=False)
    latitude = db.Column(db.Float, nullable=False)
    longitude = db.Column(db.Float, nullable=False)
    link_length_km = db.Column(db.Numeric(precision=2))
    link_length_miles = db.Column(db.Numeric(precision=2))
    estimation_method = db.Column(db.String(length=15), nullable=False)
    estimation_method_detailed = db.Column(
        db.String(length=100), nullable=False
    )
    direction_of_travel = db.Column(db.String(length=1), nullable=False)
    pedal_cycles = db.Column(db.Integer, nullable=False)
    two_wheeled_motor_vehicles = db.Column(db.Integer, nullable=False)
    cars_and_taxis = db.Column(db.Integer, nullable=False)
    buses_and_coaches = db.Column(db.Integer, nullable=False)
    lgvs = db.Column(db.Integer, nullable=False)
    hgvs_2_rigid_axle = db.Column(db.Integer, nullable=False)
    hgvs_3_rigid_axle = db.Column(db.Integer, nullable=False)
    hgvs_3_or_4_articulated_axle = db.Column(db.Integer, nullable=False)
    hgvs_4_or_more_rigid_axle = db.Column(db.Integer, nullable=False)
    hgvs_5_articulated_axle = db.Column(db.Integer, nullable=False)
    hgvs_6_articulated_axle = db.Column(db.Integer, nullable=False)
    all_hgvs = db.Column(db.Integer, nullable=False)
    all_motor_vehicles = db.Column(db.Integer, nullable=False)
