"""empty message

Revision ID: 7134a7f940f8
Revises: 0046d03e1ed4
Create Date: 2019-12-11 20:20:18.996752

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2.types


# revision identifiers, used by Alembic.
revision = "7134a7f940f8"
down_revision = "0046d03e1ed4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "aadf_by_direction",
        sa.Column(
            "point",
            geoalchemy2.types.Geometry(geometry_type="POINT", srid=4326),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aadf_by_direction", "point")
    # ### end Alembic commands ###
